### ISSUE TITLE
[Suggestion] A way to provide a containing directory other than by changing the environment variable

### ISSUE THREAD

**Issue by shepmaster** [samgiles/rs-mktemp#1]
Maybe something like

```rust
new_dir_in(&Path)
```

? 

Or maybe a structure like

```rust
TempBuilder::new()
  .in(&Path) // optional
  .file() // or .dir
```

**Comment by samgiles** [comment]
Thanks for the suggestion!  I've implemented a simple `new_dir_in` and `new_file_in` API.  Might use a builder API in the future, but wanted to keep it simple for now. 

https://samgiles.github.io/rs-mktemp/mktemp/struct.Temp.html
