### ISSUE TITLE
Provide a mechanism for retaining file

### ISSUE THREAD

**Issue by phillord** [samgiles/rs-mktemp#10]
The default behaviour is nice for writing tests since everything is cleaned up afterwards. But painful if the tests fail -- it becomes hard to debug because it's not possible to see what is in the file that you've just deleted.

It would be nice to have a mechanism to stop file deletions after, say, a panic.

**Comment by Laaas** [comment]
I don't think this is the desired behavior for every user, but I think making an environment variable for this would be nice. Something like `RS_MKTEMP_ALWAYS_RELEASE` maybe?

**Comment by phillord** [comment]
Yes, that would work; I'd have to rerun tests after failure, so it's not quite as nice as non-deletion on unsuccessful exist, but it would be a lot easier than my current solution (changing the temp file constructor for a named one).

**Comment by Laaas** [comment]
Can't you use the release method in stead of that?

**Comment by phillord** [comment]
Oh, that prevents deletion. I had assumed that "release" was equivalent to the variable going out of scope, but I see from the example, that this is wrong. My apologies for the noise.
