### ISSUE TITLE
Release flag and method are inefficient; operate by value instead

### ISSUE THREAD

**Issue by chris-morgan** [samgiles/rs-mktemp#6]
It’d be more efficient to have `release()` consume `self` and return the `PathBuf`:

```rust
pub fn release(self) -> PathBuf {
    let path = mem::replace(&mut self.path, PathBuf::new());
    mem::forget(self);
    path
}
```

That way you don’t need to allocate twice just to get the path out as a `PathBuf`.

This also allows you to scrap the flag `_release` altogether.

**Comment by samgiles** [comment]
Version 0.4.0 does something like this now! Thanks for the suggestion.
